### ISSUE TITLE
Use `Object.values` when targeting Node6

### ISSUE THREAD

**Issue by lukeed** [sindresorhus/p-props#1]
In your [todo note](https://github.com/sindresorhus/p-props/blob/master/index.js#L18), you mention using `Object.entries`, but will require de-structuring or key look-ups just to get to the values.

Using `Object.values` will return an array of the values, which can be passed directly to `Promise.all`.

It also has the same [support](http://node.green/#ES2017) as `Object.entries`.

**Comment by sindresorhus** [comment]
I don't remember exactly, but I had some reason for it. Maybe for efficiency reasons, so it wouldn't iterate the iterable twice, but then could maybe have done `Array.from()` first. I'll keep this open and we can look more into it in the future when I can target Node.js 6.
