### ISSUE TITLE
Mapper receives unresolved element value

### ISSUE THREAD

**Issue by ark120202** [sindresorhus/p-props#10]
```js
const pProps = require('p-props');
pProps({ foo: Promise.resolve('bar') }, console.log);
// => Promise {}, 'foo' 
```

Now an example from #5 doesn't work because of it. Is it an expected behavior?

**Comment by sindresorhus** [comment]
I would expect that, yes, but seems it's not documented nor tested.

**Comment by BendingBender** [comment]
@sindresorhus Can you explain me the use case for this? If you want to operate on promises, you can do this before passing them to `pProps`. I'd actually expect that `mapper` only receives resolved values and has an opportunity to produce new promises if needed.

**Comment by sindresorhus** [comment]
This was inspired by Bluebird. All my `p-*` modules behaves like this. It's just meant as a convenience.

**Comment by BendingBender** [comment]
So you would actually accept a PR that changes this behavior?

**Comment by sindresorhus** [comment]
Yes

**Comment by BendingBender** [comment]
I'll make a PR as soon as #11 is merged.
