### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by kirillgroshkov** [sindresorhus/p-props#6]
I'd like to have typings included in the package, cause I have issues with `@types/p-props`. I'd like the standard way of importing packages in Typescript to work: `import * as pProps from 'p-props'`

**Comment by sindresorhus** [comment]
PR welcome :)

Follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide).

**Comment by kirillgroshkov** [comment]
Great 🎉
