### ISSUE TITLE
Add depth

### ISSUE THREAD

**Issue by mk-pmb** [sindresorhus/p-props#8]
Hi! Could someone please add a depth option? I'd like to await a settled twin of my dictionary object of d.o. (of d.o. …) of Promises, and can't figure out how to manage the concurrency in a smart way.

**Comment by sindresorhus** [comment]
Can you provide a code example of how it would look like if `p-props` had a depth option?

**Comment by mk-pmb** [comment]
Will do, it might take a few days.

**Comment by sindresorhus** [comment]
Hmm, I feel like this is too specific to only your use-case. A `{deep: true}` option might make sense, although I'm not sure I would ever use it, but a `depth` option like you're describing is weird. If I set `{depth: 2}`, I would expect it to resolve promises for both depth 1 and depth 2.

**Comment by mk-pmb** [comment]
> If I set {depth: 2}, I would expect it to resolve promises for both depth 1 and depth 2.

Yeah, the example code should do that. I count the value of `deployment` as depth 0. Which promise wasn't resolved when you ran it with `{ depth: 2 }`?

> I feel like this is too specific to only your use-case.

No prob. When/if you decide you don't want that feature, I'll make a separate module for it.

**Comment by sindresorhus** [comment]
> When/if you decide you don't want that feature here, I'll make a separate module for it.

Yeah, probably best.
